import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Layout from '../Layouts';
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>JJAM 머랭 홈페이지</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout />
    </div>
  )
}

export default Home
